name: test angular

on:
  push:
    branches: [ "render-7" ]
  pull_request:
    branches: [ "render-7" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.21.0]

    steps:
    - uses: actions/checkout@v4

    - name: instalar dependencias
      run: npm ci, npm install --legacy-peer-deps

    - name: ejecutar pruebas
      run: |
        npm run test
